version: "3.7"
services:
  db:
    image: arifh19/restaurant-db:0.2
    networks:
      - restaurant-network
    volumes:
      - ./postgresql/pgdata:/var/lib/postgresql/data
    ports:
      - "${portDb}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: arifh19/redis-restaurant
    ports:
      - "${portRedis}:6379"
    networks:
      - restaurant-network
    volumes:
      - ./redis:/data
networks:
  restaurant-network:
